title:              Poppy's Orchard
description:        Finding daily balance in this amazing world.
lang:               en

# Site subpath, e.g. /blog
baseurl:            ""

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink: /:title/

# Site base hostname & protocol, e.g. http://example.com
url:                "http://poppysorchard.com"

# Site logo # e.g. logo.png, upload logo image file to /uploads/ folder
logo:               https://kinlane-productions2.s3.amazonaws.com/poppys-orchard/california-poppy-+pedal.png

navbar:
    sticky:         true
    search:         true
  
# Default author settings
author:
    name:           Poppy
    title:          Goddess
    avatar:         https://kinlane-productions2.s3.amazonaws.com/kin-lane/kin-lane-cartoon-questioning.png

# Author settings, displayed on post and doc pages if front matter references author name e.g. author: peter
authors:
    kin:
    name:           Poppy
    title:          Goddess
    avatar:       https://kinlane-productions2.s3.amazonaws.com/kin-lane/kin-lane-cartoon-questioning.png
    email:       'kinlane@postman.com'
    affiliation: 'Postman Open Technologies'
    github:      'kinlane'
    linkedin:    'in/kinlane'
    twitter:     'kinlane'           

# Social icons displayed in footer
social:
    email:
    website:
    facebook:       https://www.facebook.com/kinlane
    flickr:
    dribbble:
    github:         https://github.com/kinlane
    googleplus:
    instagram:     
    linkedin:       https://www.linkedin.com/in/kinlane/
    pinterest:
    twitter:        https://twitter.com/kinlane
    vimeo:          
    youtube:        

# Share button
share:
    post:           true # Display share buttons on a post page
    doc:            true # Display share buttons on a doc page
    twitter:        username # Enable by adding Twitter handle 
    facebook:       true # Enable by setting true (Facebook handle not required)

# Default footer image settings
footer:
    copyright:      Kin Lane

# Number of posts displayed on blog page
paginate:           25

# Blog path
paginate_path:      "/stories/:num/"

# Build settings
markdown:           kramdown
highlighter:        rouge

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style:            compressed

# Defaults
defaults:
  # _plants
  - scope:
      path:         ""
      type:         plants
    values:
      layout:       plants
  # _people
  - scope:
      path:         ""
      type:         people
    values:
      layout:       people
  # _places
  - scope:
      path:         ""
      type:         places
    values:
      layout:       places            

collections:
  plants:
    output:         true
  people:
    output:         true
  places:
    output:         true        